### ISSUE TITLE
OpenSubtitles Agent Makes SRT2UTF-8.bundle crash.

### ISSUE THREAD

**Issue by gmcouto** [ukdtom/SRT2UTF-8.bundle#23]
I've noticed that Srt2Utf-8 is not converting some of my subtitles anymore.
Looking on the logs I found out that it is because OpenSubtitles agent is configured for Portuguese Brasil and it inform it's language as "pb".
Looking on the code there is no entry for the "pb" language, which I think it should be included.
Even though I name my srt files as ".pt.srt", I have no control of what OpenSubtitles agent do.

Part of the log:
![screen shot 2015-06-04 at 3 56 22 pm](https://cloud.githubusercontent.com/assets/615016/7991951/4484ba68-0ad2-11e5-8825-6717905258f2.png)

**Comment by ukdtom** [comment]
Fixed in newest version
