### ISSUE TITLE
SubZero support please

### ISSUE THREAD

**Issue by royaljet** [ukdtom/SRT2UTF-8.bundle#29]
Hi Dane, can you please add support for SubZero subtitle agent as well! Thanks a lot!

**Comment by ukdtom** [comment]
Will look into this, after the next release of WebTools

**Comment by ukdtom** [comment]
Sadly delayed here.....

Doesn't work in my dev environment...

QNAP's :-(

**Comment by royaljet** [comment]
Hi, this just started working fine now, did you do something? Even if you did, I never updated any plugins, so not sure why it is working fine now?!

Any movie I add now, SubZero downloads an Arabic subtitle and the subtitle is working now. Not sure if the subtitle being downloaded is already compatible, or your plug-in is doing the magic>!

**Comment by ukdtom** [comment]
Heh....I forgot to close this ;-)

Digged into it, and Sub-Zero already has an option to force UTF-8
