### ISSUE TITLE
Agent doesn't work on TV Shows

### ISSUE THREAD

**Issue by gjerek** [ukdtom/SRT2UTF-8.bundle#35]
Firstly it doesn't even appear under Agents -> Programmes -> Personal Media Shows

I tried to add 'com.plexapp.agents.none' under contributes_to in __init__.py, 
after that it was shown in Plex, but subtitles were not changed to UTF8.

**Comment by FHD100** [comment]
No 3rd party agent appears in "Personal Media Shows", check "The Movie Database" or "TheTVDB" you will find it there. Change the agent in your library settings to either TheTVDB ro The Movie Database.

**Comment by gjerek** [comment]
I had it enabled before, and there was nothing in com.plexapp.agents.srt2utf8.log about TV shows.

**Comment by ukdtom** [comment]
4 shows, it's like @FHD100 said!

https://github.com/ukdtom/SRT2UTF-8.bundle/blob/master/Contents/Code/__init__.py#L60

And it does work, since I use it all the time ;)

**Comment by ukdtom** [comment]
And closing this for now.

Do reopen if needed
