### ISSUE TITLE
Str2Utf-8 Plugin does not appear on the TV Shows agent

### ISSUE THREAD

**Issue by Yynwarf** [ukdtom/SRT2UTF-8.bundle#37]
Hi, I've followed all the steps, but for some reason, at this point (Then make sure, that the SRT2UTF-8 agent is selected...) the Str2Utf-8 option does not show up on my list. There's just the Local Media Assets (TV) - for this only happens on the TV Shows options. On the Movies agents, this plugin shows up and works perfectly. 
How can I fix it? 

Oh, I'm accessing Plex Media Server with my PS4 and using my notebook as the server. 

P.S.: Sorry if it's hard to understand what I've said, English is not my native language. ;)

**Comment by ukdtom** [comment]
Need more details, logs as well as a screendump

**Comment by peterjnck** [comment]
Same issue here, running Plex on Synology DS418play..
![screen shot 2018-02-26 at 00 05 47](https://user-images.githubusercontent.com/36827532/36647630-fa049dfe-1a88-11e8-8c33-429676f7e6f0.png)
![screen shot 2018-02-26 at 00 06 17](https://user-images.githubusercontent.com/36827532/36647631-fa1fa482-1a88-11e8-92ea-f31bd341ed96.png)

**Comment by ukdtom** [comment]
Personal medias are not supported for shows nor movies...

**Comment by ukdtom** [comment]
Closed due to lack of response from OP

**Comment by RJanata** [comment]
@ukdtom, could you please take a look at this issue? Your plugin is available only under Movies and it does not show up under (TV) Shows. Subtitles for series are not therefore encoded into UTF8. Thanks!

**Comment by ukdtom** [comment]
Please don't dig into an issue, that was closed 2 years ago, and with a different issue...
Create a new issue, and add screenshot of where you enabled the agent
