### ISSUE TITLE
Plug-in is generating new subtitle file by randomly, it is skipping most of it.

### ISSUE THREAD

**Issue by monsterazor** [ukdtom/SRT2UTF-8.bundle#46]
Hi;
I'm from Turkey and naturally I prefer Turkish subtitles. So I have been using this plug-in for a long time and I like. But approxtimately for 1 months plug-in is generating new subtitle file by randomly, it is skipping most of it. For example it is generating a new subtitle for episode 1 and episode 3, but it is skipping episode 2. I refreshed meta-data many times but nothing wasn't changed.

I hope you fix.

**Comment by ukdtom** [comment]
Logs please, right after doing the Plex Dance on an item, and in a zip

**Comment by monsterazor** [comment]
Hi; I did Plex Dance for 2 times now, and I uploaded logs.
[Plex Media Server Logs_2020-03-20_13-24-42.zip](https://github.com/ukdtom/SRT2UTF-8.bundle/files/4358982/Plex.Media.Server.Logs_2020-03-20_13-24-42.zip)

**Comment by ukdtom** [comment]
Sadly can't use the logs, since they are without 3.Party logs :(

See: https://github.com/ukdtom/SRT2UTF-8.bundle/wiki/Troubleshooting-&-Logging

**Comment by monsterazor** [comment]
Hi again;
I guess it will be correct files for logs at this time.
[PMS Plugin Logs.zip](https://github.com/ukdtom/SRT2UTF-8.bundle/files/4360121/PMS.Plugin.Logs.zip)

**Comment by ukdtom** [comment]
Much better, now I need a filename, so I know what to look for ;)

**Comment by ukdtom** [comment]
Ping

**Comment by monsterazor** [comment]
Hello again;

Firstly sorry for delay :)
File Name: hunters.2020.s01e01.720p.web.h264-skgtv[eztv].srt

I noticed a weird situation. Normally when plug-in worked, it creates a new subtitle file with 'Srt2Utf-8' extension. And it shows as 'Unknown SRT' at plex player. It wasn't creating a new subtitle file at file directory so i opened this topic. 
But yesterday I noticed that Unknown SRT' has been at Plex Player. And it working without error. But only one subtitle file is being at directory per episode. Not Srt2Utf-8.


I uploaded my directory and plex player screenshot.
![Ek Açıklama 2020-03-26 024243](https://user-images.githubusercontent.com/55329530/77597007-9946ca00-6f0e-11ea-9cbb-6d731cee40cc.jpg)
![Screenshot_2020-03-26-02-36-38](https://user-images.githubusercontent.com/55329530/77597008-9a77f700-6f0e-11ea-8137-b3ef29db7936.png)

Same situation at other directories.
![Ek Açıklama 2020-03-26 030923](https://user-images.githubusercontent.com/55329530/77597225-3ace1b80-6f0f-11ea-8e8d-87d40b29de32.jpg)

**Comment by ukdtom** [comment]
SRT2UTF-8 skipped the file, since it was already in UTF-8

From the log:

`2020-03-18 18:08:04,107 (a68) :  DEBUG (logkit:13) - Found a valid subtitle file named "hunters.2020.s01e01.720p.web.h264-skgtv[eztv].srt"
2020-03-18 18:08:04,170 (a68) :  DEBUG (logkit:13) - The subtitle file named : E:\İndirmeler\DİZİLER\Hunters\Season 1/hunters.2020.s01e01.720p.web.h264-skgtv[eztv].srt is already encoded in utf-8, so skipping`

If the file still shows bad characters, then it's a bad sub, that was saved as utf-8, but without applying the correct encoding, and if so, I can only suggest to download an alternative sub

**Comment by monsterazor** [comment]
Hi again;
You are right. Before that all other subtitle files was converting  by plug-in and created new subtitle file. But at this situation I didn’t recognized when I saw only one subtitle file.
I understand to skipping UTF-8 files at now.
Thanks...
