### ISSUE TITLE
SRT2UTF-8.bundle not working with tv shows

### ISSUE THREAD

**Issue by ethansot** [ukdtom/SRT2UTF-8.bundle#47]
Hello I  followed all the instructions. I use opensubtitles, I don't download them. It works perfect with movies but not with any of the tv shows. Do i need to do anything else ?
<img width="495" alt="Capture1" src="https://user-images.githubusercontent.com/22742783/78511638-54bbf980-776c-11ea-9ccf-18885e28e549.PNG">
<img width="485" alt="Capture2" src="https://user-images.githubusercontent.com/22742783/78511639-55ed2680-776c-11ea-9895-3de3c89e2cbf.PNG">

**Comment by ukdtom** [comment]
In above screenshot for shows, click on the leaf for your primary show agent, like TheTVDB, and make sure SRT2UTF-8 agent is enabled, and at the bottom

**Comment by ukdtom** [comment]
Ping

**Comment by ethansot** [comment]
Thank you so much. You where right. It was on the TVDB tab. I checked the box and put it all the way to the end. I haven't tried it yet to see if its working but I'm sure it will.
