### ISSUE TITLE
I don't see this plugin in Plex agents

### ISSUE THREAD

**Issue by abu-sarah** [ukdtom/SRT2UTF-8.bundle#48]
Hi
thank you so much for developing this powerful tool. I am new to Plex and my Plex media server in NAS - Synology. This is my first plugin installed on plex. I install the bundle and put it in NAS-Synology in this path:
/Plex/Library/Application Support/Plex Media Server/Plug-ins

When I try to open Plex, I don't see it in the Plugins tab or Agents for both movies and TS Shows.

Is it because I download the different version?
Or maybe I need to install another plugin?

Plex Version 4.22.3 (2020)
SRT2UTF-8.bundle V0.0.2.5
<img width="735" alt="Screen Shot 2020-04-07 at 1 02 30 AM" src="https://user-images.githubusercontent.com/63265764/78611001-ac428e00-786e-11ea-97e8-2798bdca1b58.png">
<img width="1033" alt="Screen Shot 2020-04-07 at 1 02 51 AM" src="https://user-images.githubusercontent.com/63265764/78611011-b1074200-786e-11ea-90fc-bec91ae1fa25.png">
<img width="1082" alt="Screen Shot 2020-04-07 at 1 03 01 AM" src="https://user-images.githubusercontent.com/63265764/78611015-b2386f00-786e-11ea-83e4-33ef0d37f1c1.png">

**Comment by ukdtom** [comment]
You'll not see it in plugins, only under agents.

Also check that the rights of the .bundle directory is set to the plex user

**Comment by abu-sarah** [comment]
Thank you for fasr reply

I don't know what do you mean by "is set to the plex user recursively"

to recap: I move the plug-in bundle (SRT2UTF-8.bundle) into the Plug-Ins folder, My Plex Media Server on NAS-Synology to follow path:
/Plex/Library/Application Support/Plex Media Server/Plug-ins

I go to Plex setting ----> Agents then movies 

I don't see any things!
![Uploading Screen Shot 2020-04-07 at 12.22.33 PM.png…]()
![Uploading Screen Shot 2020-04-07 at 12.21.50 PM.png…]()

**Comment by ukdtom** [comment]
Not a Synology user, so not much help here sadly, but....

Plex on the Syno is running under a user named plex.
That user needs to have rights to SRT2UTF-8.bundle directory, as well as all files below that

If not, then PMS can't see it

**Comment by abu-sarah** [comment]
I have (Plex user) the rights permission to that plugins folder, same as media folder which include Movies and TV Shows.

I think I have to edit all SRT files to save as a function manually. The problem that I have over 500 movies!! So I think to do it 500 times. I will edit 40 files per day.

Thank you so much for trying to help me.
I wish you all the best.

**Comment by ukdtom** [comment]
Right below the SRT2UTF-8.bundle, is there a directory named "Contents" ?

And if not, you might have extracted it wrongly

**Comment by abu-sarah** [comment]
yes, there is
<img width="923" alt="Screen Shot 2020-04-07 at 2 26 08 PM" src="https://user-images.githubusercontent.com/63265764/78664054-eb5af880-78db-11ea-976a-5187f60ba7ca.png">
<img width="915" alt="Screen Shot 2020-04-07 at 2 26 20 PM" src="https://user-images.githubusercontent.com/63265764/78664059-ec8c2580-78db-11ea-8262-bfa679b37c11.png">

**Comment by ukdtom** [comment]
In the Logs/PMS Plugin Logs directory, are there any log files created for srt2utf-8 ?

If so, zip them all, and upload, and if not, restart PMS, and after 2 min, zip Logs/Plex Media Server*.log files and upload them

**Comment by abu-sarah** [comment]
Good news ukdtom

Now it's showing up in Agents after shutting down Synology for (2 minutes).

You're lifesaver، you save me a lot of time instead to do it manually  
THANK YOU ((((((SO)))))) MUCH  🙏 🌹

Now I am trying to solve the main problem to show the Arabic language in my movies but still Gibberish (Unknown language). 

* I put a mark in all SRT2UTF-8 in  Agents
* I change the settings for SRT2UTF-8 to support the Arabic language
* I change the settings for SRT2UTF-8 to support opensubtitles.org
* I refresh all metadata for movies. 

Kindly check the below settings and tell me if I did something wrong:
<img width="708" alt="Screen Shot 2020-04-07 at 9 26 38 PM" src="https://user-images.githubusercontent.com/63265764/78705922-e7000100-7916-11ea-912f-0f20dcadff1c.png">
<img width="800" alt="Screen Shot 2020-04-07 at 9 26 44 PM" src="https://user-images.githubusercontent.com/63265764/78705965-f7b07700-7916-11ea-80ab-7fd30d3ff8f8.png">
<img width="576" alt="Screen Shot 2020-04-07 at 9 26 54 PM" src="https://user-images.githubusercontent.com/63265764/78706005-06972980-7917-11ea-9354-11c50ed3a70f.png">

The subtitle show as same as before to unknown language:
<img width="1082" alt="Screen Shot 2020-04-07 at 9 27 19 PM" src="https://user-images.githubusercontent.com/63265764/78706091-2fb7ba00-7917-11ea-925a-d4796678ae26.png">

**Comment by ukdtom** [comment]
A zip of SRT2UTF-8 logs, as well as the name of a media file, so I have something to search for in the logs

**Comment by ukdtom** [comment]
Arhhh....Missed one thing ;)

Make sure, that your movie library in PMS is set to use "Plex Movie" as it's primary agent, and if using "The Movie Database", then also make sure that SRT2UTF-8 is enabled for that as well

**Comment by abu-sarah** [comment]
Thank for fast reply

I am using "Plex Movie" as my primary agent in movies library:

<img width="722" alt="Screen Shot 2020-04-07 at 10 59 55 PM" src="https://user-images.githubusercontent.com/63265764/78714422-85df2a00-7924-11ea-88c5-7fff5bf1aa50.png">

and I enable SRT2UTF-8 at all "Plex Movie, Personal Media, and The Movie Database":

<img width="1072" alt="Screen Shot 2020-04-07 at 11 06 18 PM" src="https://user-images.githubusercontent.com/63265764/78714583-d0f93d00-7924-11ea-8868-68baac269fb3.png">
<img width="1042" alt="Screen Shot 2020-04-07 at 11 06 29 PM" src="https://user-images.githubusercontent.com/63265764/78714609-db1b3b80-7924-11ea-8404-72c6d0f64563.png">

**Comment by abu-sarah** [comment]
It's working now

I just need to force metadata for a couple of hours, It's taking for me about 3 and a half hour.

the overall solution for fixing subtitles on Synology PMS:
1- Download SRT2UTF-8 in Zip file and unzip to be like "SRT2UTF-8.bundle" without "Master" word.
2- Move to this path:
/Plex/Library/Application Support/Plex Media Server/Plug-ins
<img width="926" alt="Screen Shot 2020-04-08 at 5 24 12 AM" src="https://user-images.githubusercontent.com/63265764/78738016-81813400-7959-11ea-83a6-cb6dc23dc33f.png">

3- Shutdown Synology for about 2 minutes - at minimum - then turn it on.
4- Go to PMS Agents and enable SRT2UTF-8 in all Agents especially the main "Plex Movie"
<img width="1057" alt="Screen Shot 2020-04-08 at 5 24 43 AM" src="https://user-images.githubusercontent.com/63265764/78738083-9a89e500-7959-11ea-8605-86b4210a3a2e.png">

5- Go the SRT2UTF-8 Setting and enable (support opensubtitles.org and choose the language).
<img width="567" alt="Screen Shot 2020-04-08 at 5 24 56 AM" src="https://user-images.githubusercontent.com/63265764/78738102-ad9cb500-7959-11ea-9af5-efd4fc5e9815.png">

6- Put the SRT2UTF-8 at the bottom of the list.
<img width="1057" alt="Screen Shot 2020-04-08 at 5 24 43 AM" src="https://user-images.githubusercontent.com/63265764/78738202-f0f72380-7959-11ea-9139-2212faa94c1b.png">

7- Force Metadata by using "Refresh all Metadata" and wait to finish (Maybe will take a few hours depends on number of movies).
8- Enjoy the movie.
<img width="775" alt="Screen Shot 2020-04-08 at 5 32 09 AM" src="https://user-images.githubusercontent.com/63265764/78738358-56e3ab00-795a-11ea-96ca-cc84308d7ad0.png">

Thank you ukdtom
