### ISSUE TITLE
How are user-uploaded subtitles handled?

### ISSUE THREAD

**Issue by pentago** [ukdtom/SRT2UTF-8.bundle#49]
Just noticed that subtitles I upload to Plex via web interface still aren't displayed properly.

How to achieve this?

**Comment by ukdtom** [comment]
Sadly not supported :(

And also will never happen, since plugins is a dying race, so not worth it

All I can suggest, is that you, if you upload via Plex interface, check the sub first, with something like:
https://www.nikse.dk/subtitleedit/
