### ISSUE TITLE
Not working with Early access

### ISSUE THREAD

**Issue by Saceek** [ukdtom/SRT2UTF-8.bundle#51]
Hello ukdtom!

Firstly thanks a lot for your nice work! I tried yesterday the early access to new version of plex player and unfortunately character encoding was wrong again, when i get back to current stable version (not early access) everything work just fine again. Any ideas? Do you know about changes in early access version? Thanks a lot for helping, Tomáš

**Comment by ukdtom** [comment]
Define Early Access Client

**Comment by Saceek** [comment]
Hello,

It is an Plex app at Xbox One X. 
Client Version 5.1.1, 
Platform Version 10.0.19041.3503

It is sufficent?
Thanks a lot

**Comment by ukdtom** [comment]
Then you should go to Plex Forums, and report it there, since nothing changed for SRT2UTF-8, so have to be a bug in their new version

As such, closing this
