### ISSUE TITLE
Wiki - "plug-in directory" link is broken

### ISSUE THREAD

**Issue by javespi** [ukdtom/SRT2UTF-8.bundle#53]
Hi,

I was following the [Installation wiki page](https://github.com/ukdtom/SRT2UTF-8.bundle/wiki/Installation) and the link to know where to find the plugins folder points to Zendesk of Plex which is broken requiring username and password.

I found this other support article from Plex.tv which I guess it has the same content as the previous one in the past:
https://support.plex.tv/articles/201106098-how-do-i-find-the-plug-ins-folder/

I would love to open a pull-request suggesting the change, but Github doesn't provide a easy way to do it 🙏 

Thank you for the plugin and the wiki! Very helpful

Cheers

**Comment by haarismemon** [comment]
Hey @javespi 

Good spot! I've now updated the installation wiki page with the updated link for where to find the plug-ins folder.

If you believe that this issue has been fixed, please go ahead and close the issue :)

Thanks

**Comment by ukdtom** [comment]
Closing due to lack of response

**Comment by javespi** [comment]
Thanks for the quick fix! @haarismemon
