### ISSUE TITLE
Plex don't see the plugin.

### ISSUE THREAD

**Issue by kolunio82** [ukdtom/SRT2UTF-8.bundle#56]
Hi. I unpacked zip to C:\Users\username\AppData\Local\Plex Media Server\Plug-ins\SRT2UTF-8.bundle-master but in agents plugin is not visible, What i did wrong?

**Comment by ukdtom** [comment]
Remove -master from the directory name

Ref: https://github.com/ukdtom/SRT2UTF-8.bundle/wiki/Installation
